### ISSUE TITLE
SlimRom 6.0 Marshmallow for Huawei P8 Lite

### ISSUE THREAD

**Issue by hak86** [hak86/android_device_hisi_hi6210sft#1]
Hi folks
I almost finish with SlimRom based on the lates source of Android 6.0.1 Marshmallow branch and will be available once fix bt issue that almost done (hope for today, if not will be available from tomorrow, even if bt is not working as first build).
# Working Hardware:

- [x] Audio.
- [x] Camera.
- [x] Display.
- [x] GPS.
- [x] Graphics.
- [x] Lights.
- [x] NFC.
- [x] RIL.
- [x] Sepolicy (will be implemented in the future).
- [x] Sensors.
- [x] Storage: both internal and external.
- [x] Sound Trigger Module ported from Honor 6 "h60".
- [x] Wifi.

# Bugs

- Bluetooth.
- Camera: it's work both recording and selfies on stock camera application, for recording it's record up to 720 for now I guess it's an issue with media_profiles and media_codecs.

![screenshot_20170725-112531](https://user-images.githubusercontent.com/6603252/28582709-ad7fcbc8-7166-11e7-8ad8-39db4dc5f55b.png)

**Comment by redmusicxd** [comment]
What is the problem with the bt, a2dp, connect or what cause i builded the slimrom a couple hours ago and the enable works also the mac address.

**Comment by hak86** [comment]
with my tree or OpenKirin? @redmusicxd here the logcat
https://github.com/hak86/pastebin/blob/master/slim-mm.txt

**Comment by redmusicxd** [comment]
with your tree, this tree

**Comment by redmusicxd** [comment]
i dont know why the wifi mac doesnt show but i will look over the log

**Comment by redmusicxd** [comment]
and also did you know that yt 720p60 it' working(actually on video quality menu doesnt say 720p60 it says 720p

**Comment by hak86** [comment]
@redmusicxd wifi is fine, the ramdisk of OpenKirin was miss some implementation to run, imagine same thing for bluetooth, for video recording is working can record up to 720 with audio, when i choose 1080 the application is gonan to crash and might git got to fix..the only issue is playing video like a multiple surveillance  monitors huahuah..
![screenshot_20170725-135334](https://user-images.githubusercontent.com/6603252/28585608-07717ef6-7171-11e7-8587-4e35cbb15e8f.png)

**Comment by redmusicxd** [comment]
did you see if you try to record with Footej Camera with Frontal Camera works perfect at 720p but with Back Camera after on play it's freezed for 4 seconds so i dont know i was thinking it's something about focus
