### ISSUE TITLE
Graphics Drivers?

### ISSUE THREAD

**Issue by hak86** [hak86/android_device_hisi_hi6210sft#6]
After i rename the device to android_device_hisi_hi6210sft i got this 2 files in the out/device/hisi/hi6210sft/

- graphics.o
- graphics.P

are required for booting?
![screenshot from 2016-04-07 11-58-58](https://cloud.githubusercontent.com/assets/6603252/14347658/884553b0-fcb8-11e5-94a5-d2ce549779cd.png)

**Comment by XePeleato** [comment]
Leave them like that, I never  had any issue with those files

**Comment by hak86** [comment]
I got cm-12.1 booting.
